CREATE TABLE trips (
    trip_id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    origin_station TEXT NOT NULL,
    destination_station TEXT NOT NULL,
    start_datetime TIMESTAMP,
    end_datetime TIMESTAMP,
    is_project BOOLEAN DEFAULT FALSE NOT NULL,
    utc_start_datetime TIMESTAMP,
    utc_end_datetime TIMESTAMP,
    estimated_trip_duration FLOAT,
    manual_trip_duration FLOAT,
    trip_length FLOAT NOT NULL,
    operator TEXT,
    countries TEXT,
    line_name TEXT,
    created TIMESTAMP,
    last_modified TIMESTAMP,
    trip_type TEXT,
    material_type TEXT,
    seat TEXT,
    reg TEXT,
    waypoints TEXT,
    notes TEXT,
    price FLOAT,
    currency TEXT,
    ticket_id INT,
    purchase_date TIMESTAMP
);
